acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

book/urls.py
from django.urls import path
from . import views
app_name = "book"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('vote/', include("vote.urls")),
    path('book/', include("book.urls")),
    path('trans/', include("trans.urls")),
    path('pdfread/', include("pdfread.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ctrl+shift+p > select interpreter > path 찾기
# Scripts > python.exe

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote"),
    path('cancel/<tpk>', views.cancel, name="cancel"),
    path('create/', views.create, name="create"),
    path('delete/<tpk>', views.delete, name="delete")
]

vote/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 10:
            return f"{self.content[:10]} ..."
        return self.content 


class Sel(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    sname = models.CharField(max_length=100)
    spic = models.ImageField(upload_to="vote/%y/%m")
    scon = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.topic}_{self.sname}"

vote/views.py
from django.shortcuts import render,redirect
from .models import Topic, Sel
from django.utils import timezone
from django.contrib import messages
# Create your views here.

def delete(request, tpk):
    t = Topic.objects.get(id=tpk)
    if t.maker == request.user:
        s = t.sel_set.all()
        for i in s:
            i.spic.delete()
        t.delete()
    else:
        messages.warning(request, "법적 조치 가하겠음 그만해라")
    return redirect("vote:index")


def create(request):
    if request.method == "POST":
        t = request.POST.get("top")
        c = request.POST.get("con")
        sn = request.POST.getlist("sname")
        sc = request.POST.getlist("scon")
        sp = request.FILES.getlist("spic")
        t = Topic(subject=t, content=c, 
        maker=request.user, pubdate=timezone.now())
        t.save()
        for name, con, pic in zip(sn,sc,sp):
            Sel(topic=t, sname=name, spic=pic, scon=con).save()
        return redirect("vote:index")
    return render(request, "vote/create.html")

def cancel(request, tpk):
    u = request.user
    t = Topic.objects.get(id=tpk)
    t.voter.remove(request.user)
    # t.sel_set.get(choicer=request.user).choicer.remove(request.user)
    u.sel_set.get(topic=t).choicer.remove(u)
    return redirect("vote:detail", tpk)

  



def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        spk = request.POST.get("sel")
        s = Sel.objects.get(id=spk)
        s.choicer.add(request.user)
    return redirect("vote:detail", tpk)


def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    s = t.sel_set.all()
    context = {
        "t" : t,
        "sset" : s
    }
    return render(request, "vote/detail.html", context)


def index(request):
    t = Topic.objects.all()
    context = {
        "tset" : t
    }
    return render(request, "vote/index.html",context)

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container mt-5 mb-5">
            <h1><b>토픽생성</b></h1>

            <input type="text" name="top" class="form-control mt-5" placeholder="TOPIC 제목을 입력하세요">
            <textarea class="form-control mt-4" name="con" placeholder="TOPIC 에 관해서 간단하게 설명해주세요" style="height: 150px;"></textarea>

            <div class="text-end mt-4">
                <button class="btn btn-secondary" type="button" onclick="makesel()">보기생성</button>
                <button class="btn btn-dark">토픽생성</button>
            </div>

            <div id="here" class="row mt-5">
            </div>
        </div>
    </form>


    <script>
        function makesel(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-lg-4 mt-5");
            n.innerHTML = '<input type="text" name="sname" class="form-control" placeholder="보기이름입력">\
                <input type="file" name="spic" class="form-control mt-3 mb-3">\
                <textarea placeholder="보기설명" name="scon" class="form-control"></textarea>';
            d.appendChild(n);
        }
    </script>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}

{% load mathfilters %}
    <div class="container mt-5 mb-5">

        <h1><b>{{ t.subject }}</b></h1>

        <div class="row mt-5">
            <div class="col-lg-8">
                <textarea class="form-control" style="height: 200px;" disabled>{{ t.content }}</textarea>
            </div>
            <div class="col-lg-4">
                <img src="{{ t.maker.getpic }}" style="width:100%">
                <div class="text-center mt-3">
                    <h5>created by <b>{{ t.maker }}</b></h5>
                </div>
            </div>
        </div>


        <div class="text-end mt-4 mb-4">
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
                와드
            </button>
        </div>

        <hr>


        {% if user in t.voter.all %}
            <div class="row">
                {% for i in sset %}
                    <div class="col-lg-4 mt-5">
                        <div class="form-check text-center mb-2">
                            <h6><b>{{ i.sname }}</b></h6>
                        </div>
                        <div class="progress mt-3 mb-3">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ i.choicer.count | div:t.voter.count | mul:100 | floatformat:2 }}%">{{ i.choicer.count | div:t.voter.count | mul:100 | floatformat:2 }} %</div>
                        </div>
                        <img src="{{ i.spic.url }}" width="100%">
                        <textarea class="form-control mt-3" disabled>{{ i.scon }}</textarea>
                    </div>
                {% endfor %}
            </div>

            <div class="text-center mt-4 mb-5">
                <a class="btn btn-danger" href="{% url 'vote:cancel' t.id %}" style="width: 100%;">무르기</a>
            </div>
        {% else %}
            <form method="post" action="{% url 'vote:vote' t.id %}">
                {% csrf_token %}
                <div class="row">
                    {% for i in sset %}
                        <div class="col-lg-4 mt-5">
                            <div class="form-check text-center mb-2">
                                <input class="form-check-input" type="radio" name="sel" value="{{ i.id }}" id="flexRadioDefault1">
                                <label class="form-check-label" for="flexRadioDefault1">
                                    <h6><b>{{ i.sname }}</b></h6>
                                </label>
                            </div>
                            <img src="{{ i.spic.url }}" width="100%">
                            <textarea class="form-control mt-3" disabled>{{ i.scon }}</textarea>
                        </div>
                    {% endfor %}
                </div>

                <div class="text-center mt-4 mb-5">
                    <button class="btn btn-dark" style="width: 100%;">투표하기</button>
                </div>
            </form>
        {% endif %}
    </div>




    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">즐겨찾기 추가 알림창</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
    
                        <div class="text-end">
                            <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
                            <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                        </div>
                        <textarea class="form-control mt-3 mb-3" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                    
    
                        <input type="hidden" name="sname" value="[VOTE]::{{t.subject}}">
                        <input type="hidden" name="surl" value="{{request.path}}">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-warning">추가</button>
                    </div>
                </div>
            </div>
        </div>
    </form>







{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}
    
    <div class="container mt-5 mb-5">
        <h1><b>투표소</b></h1>

        <div class="text-end">
            <a class="btn btn-dark" href="{% url 'vote:create' %}">TOPIC생성</a>
        </div>


        <div class="row">
            {% for i in tset %}
                <div class="col-lg-4 mt-5">
                    <div class="card">
                        <img src="{{ i.maker.getpic }}" class="card-img-top" alt="...">
                        <div class="card-body text-center" {% if user in i.voter.all %} style="background-color: beige;" {% endif %}>
                            <h5 class="card-title"><b>{{ i.subject }}</b></h5>
                            <p class="card-text">{{ i.summary }}</p>
                            <a href="{% url 'vote:detail' i.id %}" class="btn btn-dark">{% if user in i.voter.all %}결과보기{% else %}투표하기{% endif %}</a>
                            {% if user == i.maker %}
                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal{{forloop.counter}}">
                                    토픽삭제
                                </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


        {% for i in tset %}
            <div class="modal fade" id="modal{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">토픽 삭제 알림창</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            {{ i.voter.count }} 명이 응답했습니다. 그래도 삭제하시겠습니까?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                            <a href="{% url 'vote:delete' i.id %}" class="btn btn-danger">삭제</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}