acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>' , views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>' , views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey")
]

book/urls.py
from django.urls import path
from . import views
app_name = "book"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('vote/', include("vote.urls")),
    path('book/', include("book.urls")),
    path('trans/', include("trans.urls")),
    path('pdfread/', include("pdfread.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ctrl+shift+p > select interpreter > path 찾기
# Scripts > python.exe

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")
    pubdate = models.DateTimeField()

    def __str__(self):
        return f"{self.subject} written by {self.writer}"

    def summary(self):
        if len(self.content) > 100:
            return f"{self.content[:100]} ..."
        return self.content

    def hot(self):
        if len(self.likey.all()) > 100:
            return True
        return False


class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.board}_{self.replyer}"

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages

# Create your views here.

def unlikey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user) # likey 가 user 레코드들의 세트로 관리된다.
    return redirect("board:detail", bpk)

def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user) # likey 가 user 레코드들의 세트로 관리된다.
    return redirect("board:detail", bpk)


def index(request):
    pg = request.GET.get("page", 1)
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            from acc.models import User
            try:
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            b = Board.objects.none()
            messages.warning(request,"법적 조치 가하겠음 그만해라!!")
    else:
        b = Board.objects.all()

    
    pag = Paginator(b, 5)
    
    obj = pag.get_page(pg)
    context = {
        "bset":obj,
        "kw":kw,
        "cate":cate
    }
    return render(request, "board/index.html", context)



def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if r.replyer == request.user:
        r.delete()
    else:
        messages.warning(request,"법적 조치 가하겠음 그만해라!!")
    return redirect("board:detail", bpk)


def creply(request, bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get("com")
    Reply(board=b, replyer=request.user, comment=c).save()
    return redirect("board:detail", bpk)


def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if b.writer != request.user:
        messages.warning(request,"법적 조치 가하겠음 그만해라!!")
        return redirect("board:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject = s
        b.content = c
        b.save()
        return redirect("board:detail", bpk)

    context = {
        "b" : b
    }
    return render(request, "board/update.html", context)

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s, content=c, 
        writer=request.user, pubdate=timezone.now()).save()
        return redirect("board:index")
    return render(request, "board/create.html")

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer == request.user:
        b.delete()
    else:
        messages.warning(request,"법적 조치 가하겠음 그만해라!!")
    return redirect("board:index")

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b":b,
        "rset":r
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
<div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
    <h1><b>게시글 작성</b></h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">SUBJECT</label>
            <input type="text" name="sub" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">WRITER</label>
            <input type="text" class="form-control" value="{{ user }}" disabled>
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" name="con" style="height: 150px;"></textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">생성</button>
        </div>
    </form>
</div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}

<div class="container mt-5 mb-5">
    <h1><b>{{ b.subject }}</b></h1>

    <div class="row mt-5">
        <div class="col-lg-8">
            <textarea class="form-control" disabled style="height: 300px;">{{ b.content }}</textarea>
        </div>
        <div class="col-lg-4">
            <img src="{{ b.writer.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h4>written by <b>{{ b.writer |upper }}</b></h4>
            </div>
            <div class="text-end mt-3">
                {{ b.pubdate | date:'Y년 n월 j일 H:i'}}
            </div>
        </div>
    </div>


    <div class="text-end mt-4">
        <a href="{% url 'board:index' %}"><button class="btn btn-dark">메인</button></a>
        {% if user == b.writer %}
            <a href="{% url 'board:update' b.id %}"><button class="btn btn-secondary">수정</button></a>
            <a href="{% url 'board:delete' b.id %}"><button class="btn btn-danger">삭제</button></a>
    
        {% endif %}
    </div>

    <div class="text-end mt-4">
        <!-- {% for i in b.likey.all %}
            {{i}}
        {% endfor %}
        님이 좋아합니다. -->

        {% if user in b.likey.all %}
            <a href="{% url 'board:unlikey' b.id %}" class="btn btn-danger">좋아요 취소</a>
        {% else %}
            <a href="{% url 'board:likey' b.id %}" class="btn btn-primary">좋아요</a>
        {% endif %}    

        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
            즐겨찾기
        </button>

    </div>






    <hr>

    <form method="post" action="{% url 'board:creply' b.id %}">
        {% csrf_token %}
        <div class="row mt-5">
            <div class="col-lg-10">
                <input type="text" name="com" class="form-control">
            </div>
            <div class="col-lg-2">
                <button class="btn btn-dark" style="width: 100%;">댓글작성</button>
            </div>
        </div>
    </form>



    <div class="mt-5">
    {% if rset %}
        <div class="row">
            {% for i in rset %}
                <div class="col-lg-4 text-center mt-4">
                    <img src="{{ i.replyer.getpic }}" width="100%">
                    <div class="mt-3">
                        <h5><b>{{ i.replyer }}</b></h5>
                    </div>
                </div>
                <div class="col-lg-8 mt-4">
                    <textarea class="form-control" style="height: 150px;" disabled>{{ i.comment }}</textarea>

                    <div class="text-end mt-4">
                        {% if i.replyer == user %}
                            <a href="{% url 'board:dreply' b.id i.id %}" class="btn btn-danger">댓글삭제</a>
                        {% endif %}
                    
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>첫번째 댓글을 달아주세요 🤣</h3>
    {% endif %}
    </div>

</div>


<form method="post" action="{% url 'book:create' %}">
    {% csrf_token %}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">즐겨찾기 추가 알림창</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <div class="text-end">
                        <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
                        <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                    </div>
                    <textarea class="form-control mt-3 mb-3" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                

                    <input type="hidden" name="sname" value="[BOARD]::{{b.subject}}">
                    <input type="hidden" name="surl" value="{{request.path}}">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-warning">추가</button>
                </div>
            </div>
        </div>
    </div>
</form>


{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}
{% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>게시판</b></h1>

        <div class="text-end">
            <a href="{% url 'board:create' %}" class="btn btn-dark">CREATE</a>
        </div>


        <!-- 테이블 -->
        <table class="table mt-3 table-hover">
            <thead style="background-color: black; color:white; font-size: 20px;">
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">SUMMARY</th>
                    <th scope="col">WRITER</th>
                    <th scope="col">LIKEY</th>
                </tr>
            </thead>
            <tbody>
                {% if bset %}
                    {% for i in bset %}
                        <tr {% if i.hot %} style="background-color: antiquewhite;" {% endif %}>
                            <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                            <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                            <td>{{ i.summary }}</td>
                            <td>{{ i.writer }}</td>
                            <td>{{ i.likey.all.count }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    {% if kw %}
                        <tr>
                            <th colspan="5">검색결과가 없습니다 🎭</th>
                        </tr>
                    {% else %}
                        <tr>
                            <th colspan="5">게시글이 존재하지 않습니다 😂</th>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>

        <nav id="pag" class="mt-5" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">

                {% if bset.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1&cate={{cate}}&kw={{kw}}">처음</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{bset.previous_page_number}}&cate={{cate}}&kw={{kw}}">이전</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">처음</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">이전</a>
                    </li>
                {% endif %}
                
                
                {% for i in bset.paginator.page_range %}
                    {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
                        <li class="page-item {% if bset.number == i %}active{% endif %}">
                            <a class="page-link" href="?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a>
                        </li>
                    {% endif %}
                {% endfor %}


                {% if bset.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{bset.next_page_number}}&cate={{cate}}&kw={{kw}}">다음</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}">마지막</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">다음</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">마지막</a>
                    </li>
                {% endif %}
                


            </ul>
        </nav>


        <form>
            <div class="row mt-3">
                <div class="col-lg-2">
                    <select name="cate" class="form-select" aria-label="Default select example">
                        <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                        <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                        <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                    </select>
                </div>
                <div class="col-lg-9">
                    <input type="text" name="kw" value="{{kw}}" class="form-control">
                </div>
                <div class="col-lg-1">
                    <button class="btn btn-dark">검색</button>
                </div>
            </div>
        </form>



    </div>




    <style>
        .sub {
            color:black;
            text-decoration: none;
            font-weight: bold;
            font-size: 19px;
        }
        .sub:hover{
            color:red;
        }
    </style>


{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
<div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
    
    <h1><b>게시글수정</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">SUBJECT</label>
            <input type="text" name="sub" value="{{ b.subject }}" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">WRITER</label>
            <input type="text" class="form-control" disabled value="{{ b.writer }}">
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" name="con" style="height: 150px;">{{ b.content }}</textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">수정</button>
        </div> 
    </form>
</div>
{% endblock %}